### PR TITLE
Use correlation_id from returned options in RPC.Client

### PR DESCRIPTION
**Pull request by take-five**
Some RPC Clients might want to be able to control or use
generated `correlation_id` (e.g., log sent `correlation_id`
or use it to track request-response duration). I think exposing
generated `correlation_id` from `Hare.RPC.Client` to custom clients
would break encapsulation, but we can allow clients to
generate their own `correlation_id`. Thus they'll be able to
customize request-response lifecycle even more.

### CODE REVIEW

**Comment by take-five** [comment]
@jcabotc There have been a lots of changes in `hare` since version 0.1.9 was released. Perhaps it's time to release version 0.2.0? 😃

**Comment by jcabotc** [comment]
@take-five I agree that even tough it breaks encapsulation, it may be a good idea to do some changes to expose the generated correlation id for logging purposes. But I don't think is a good idea to allow the user to provide it's own correlation id.

The only reason I can think of to need custom correlation ids is to encode some business logic information into the correlation id to receive it back and use it instead of keep some state in the caller, which I think is a bad practice.

The correlation id should not leak to the user in any way except for debugging or logging.

Regarding 0.2.0, maybe I'll do it soon. Sorry for not being very active on the project lately, I've got a new job where I'm not using AMQP anymore, hence I've lost some motivation to improve the library. But I like the project and I hope to get the motivation to keep improving it soon.

**Comment by take-five** [comment]
> The correlation id should not leak to the user in any way except for debugging or logging.

Well, we need some request identifier to:
1) Measure, how long did it take to perform certain request (the only way I see it's achievable is to keep pending requests in state of Hare.RPC.Client callback module)
2) Log correlation_id on both client and server side
3) Provide some identifier for OpenTracing (not now, perhaps later), I thought `correlation_id` might be used for this purpose too

So I thought that having `correlation_id` in callback module would be useful for aforementioned purposes. I didn't like the idea of injecting generated `correlation_id` into `meta` object that we pass later to callback functions, so I thought that maybe it can be done in inverse way.

**Comment by take-five** [comment]
> I agree that even tough it breaks encapsulation, it may be a good idea to do some changes to expose the generated correlation id for logging purposes

Sorry, I missed that part. What is the most OK way to expose correlation_id? Via `meta` object?

**Comment by take-five** [comment]
@jcabotc I've changed the way it works: now `correlation_id` is generated before calling `before_request/5` callback, so the callback module can use it

**Pull request merged**
